# [tls.stores]
#   [tls.stores.default]
#     [tls.stores.default.defaultCertificate]
#       certFile = "/cert/_.mysite.com.crt"
#       keyFile = "/cert/_.mysite.com.key"

# [[tls.certificates]]
#   certFile = "/cert/_.mysite.com.crt"
#   keyFile = "/cert/_.mysite.com.key"
